# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flow_check.ui'
#
# Created: Tue Oct 16 15:29:05 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Tab8(object):
    def setupUi(self, tab_8):
        tab_8.setObjectName("tab_8")
        self.gridLayout_13 = QtGui.QGridLayout(tab_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 10, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(tab_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.edit_flow_ini = QtGui.QTextEdit(self.groupBox_9)
        self.edit_flow_ini.setMinimumSize(QtCore.QSize(0, 300))
        self.edit_flow_ini.setObjectName("edit_flow_ini")
        self.verticalLayout_7.addWidget(self.edit_flow_ini)
        self.gridLayout_13.addWidget(self.groupBox_9, 8, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(tab_8)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_17 = QtGui.QLabel(self.groupBox_14)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_14)
        self.label_18.setObjectName("label_18")
        self.gridLayout_14.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_14)
        self.label_19.setObjectName("label_19")
        self.gridLayout_14.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_msh = QtGui.QLabel(self.groupBox_14)
        self.label_msh.setObjectName("label_msh")
        self.gridLayout_14.addWidget(self.label_msh, 2, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_14)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_ngh = QtGui.QLabel(self.groupBox_14)
        self.label_ngh.setObjectName("label_ngh")
        self.gridLayout_14.addWidget(self.label_ngh, 3, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_14)
        self.label_21.setObjectName("label_21")
        self.gridLayout_14.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_mtr = QtGui.QLabel(self.groupBox_14)
        self.label_mtr.setObjectName("label_mtr")
        self.gridLayout_14.addWidget(self.label_mtr, 4, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_14)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_bcd = QtGui.QLabel(self.groupBox_14)
        self.label_bcd.setObjectName("label_bcd")
        self.gridLayout_14.addWidget(self.label_bcd, 5, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_14)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_tbc = QtGui.QLabel(self.groupBox_14)
        self.label_tbc.setObjectName("label_tbc")
        self.gridLayout_14.addWidget(self.label_tbc, 6, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_14)
        self.label_24.setObjectName("label_24")
        self.gridLayout_14.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_tic = QtGui.QLabel(self.groupBox_14)
        self.label_tic.setObjectName("label_tic")
        self.gridLayout_14.addWidget(self.label_tic, 7, 1, 1, 1)
        self.lineEdit_tic = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_tic.setReadOnly(True)
        self.lineEdit_tic.setObjectName("lineEdit_tic")
        self.gridLayout_14.addWidget(self.lineEdit_tic, 7, 3, 1, 1)
        self.lineEdit_tbc = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_tbc.setReadOnly(True)
        self.lineEdit_tbc.setObjectName("lineEdit_tbc")
        self.gridLayout_14.addWidget(self.lineEdit_tbc, 6, 3, 1, 1)
        self.lineEdit_bcd = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_bcd.setReadOnly(True)
        self.lineEdit_bcd.setObjectName("lineEdit_bcd")
        self.gridLayout_14.addWidget(self.lineEdit_bcd, 5, 3, 1, 1)
        self.lineEdit_mtr = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_mtr.setReadOnly(True)
        self.lineEdit_mtr.setObjectName("lineEdit_mtr")
        self.gridLayout_14.addWidget(self.lineEdit_mtr, 4, 3, 1, 1)
        self.lineEdit_ngh = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_ngh.setReadOnly(True)
        self.lineEdit_ngh.setObjectName("lineEdit_ngh")
        self.gridLayout_14.addWidget(self.lineEdit_ngh, 3, 3, 1, 1)
        self.lineEdit_msh = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_msh.setReadOnly(True)
        self.lineEdit_msh.setObjectName("lineEdit_msh")
        self.gridLayout_14.addWidget(self.lineEdit_msh, 2, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_14)
        self.label_25.setObjectName("label_25")
        self.gridLayout_14.addWidget(self.label_25, 0, 3, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_14, 0, 0, 1, 1)

        self.retranslateUi(tab_8)

    def retranslateUi(self, tab_8):
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Tab8", "Flow.ini Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("Tab8", "Flow.ini Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Tab8", "File Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Tab8", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Tab8", "Elements (.msh)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_msh.setText(QtGui.QApplication.translate("Tab8", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Tab8", "Neighbours (.ngh)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ngh.setText(QtGui.QApplication.translate("Tab8", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Tab8", "Materials (.mtr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mtr.setText(QtGui.QApplication.translate("Tab8", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Tab8", "Boundary cond. (.bcd)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bcd.setText(QtGui.QApplication.translate("Tab8", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Tab8", "Transport BC (.tbc)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tbc.setText(QtGui.QApplication.translate("Tab8", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Tab8", "Individual substances (.tic)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tic.setText(QtGui.QApplication.translate("Tab8", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Tab8", "Given Path (from flow.ini)", None, QtGui.QApplication.UnicodeUTF8))

