# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meshsettings.ui'
#
# Created: Thu Jan 31 10:54:20 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MeshSettings(object):
    def setupUi(self, MeshSettings):
        MeshSettings.setObjectName(_fromUtf8("MeshSettings"))
        MeshSettings.resize(666, 639)
        self.horizontalLayout = QtGui.QHBoxLayout(MeshSettings)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mesh_control = QtGui.QGroupBox(MeshSettings)
        self.mesh_control.setMinimumSize(QtCore.QSize(250, 527))
        self.mesh_control.setMaximumSize(QtCore.QSize(250, 16777215))
        self.mesh_control.setObjectName(_fromUtf8("mesh_control"))
        self.gridLayout_3 = QtGui.QGridLayout(self.mesh_control)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.button_mesh_import_all = QtGui.QPushButton(self.mesh_control)
        self.button_mesh_import_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_import_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_import_all.setObjectName(_fromUtf8("button_mesh_import_all"))
        self.gridLayout_3.addWidget(self.button_mesh_import_all, 0, 0, 1, 1)
        self.button_mesh_remove_all = QtGui.QPushButton(self.mesh_control)
        self.button_mesh_remove_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_remove_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_remove_all.setObjectName(_fromUtf8("button_mesh_remove_all"))
        self.gridLayout_3.addWidget(self.button_mesh_remove_all, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 11, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mesh_radio_x = QtGui.QRadioButton(self.groupBox)
        self.mesh_radio_x.setMaximumSize(QtCore.QSize(76, 16777215))
        self.mesh_radio_x.setObjectName(_fromUtf8("mesh_radio_x"))
        self.horizontalLayout_4.addWidget(self.mesh_radio_x)
        self.mesh_radio_y = QtGui.QRadioButton(self.groupBox)
        self.mesh_radio_y.setObjectName(_fromUtf8("mesh_radio_y"))
        self.horizontalLayout_4.addWidget(self.mesh_radio_y)
        self.mesh_radio_z = QtGui.QRadioButton(self.groupBox)
        self.mesh_radio_z.setObjectName(_fromUtf8("mesh_radio_z"))
        self.horizontalLayout_4.addWidget(self.mesh_radio_z)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 1, 1, 1)
        self.button_mesh_rem_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_over.setObjectName(_fromUtf8("button_mesh_rem_over"))
        self.gridLayout_4.addWidget(self.button_mesh_rem_over, 2, 1, 1, 1)
        self.button_mesh_imp_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_bellow.setObjectName(_fromUtf8("button_mesh_imp_bellow"))
        self.gridLayout_4.addWidget(self.button_mesh_imp_bellow, 3, 0, 1, 1)
        self.button_mesh_rem_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_bellow.setObjectName(_fromUtf8("button_mesh_rem_bellow"))
        self.gridLayout_4.addWidget(self.button_mesh_rem_bellow, 3, 1, 1, 1)
        self.button_mesh_imp_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_through.setObjectName(_fromUtf8("button_mesh_imp_through"))
        self.gridLayout_4.addWidget(self.button_mesh_imp_through, 4, 0, 1, 1)
        self.button_mesh_rem_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_through.setObjectName(_fromUtf8("button_mesh_rem_through"))
        self.gridLayout_4.addWidget(self.button_mesh_rem_through, 4, 1, 1, 1)
        self.button_mesh_imp_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_over.setMinimumSize(QtCore.QSize(102, 0))
        self.button_mesh_imp_over.setObjectName(_fromUtf8("button_mesh_imp_over"))
        self.gridLayout_4.addWidget(self.button_mesh_imp_over, 2, 0, 1, 1)
        self.edit_mesh_crd = QtGui.QLineEdit(self.groupBox_4)
        self.edit_mesh_crd.setObjectName(_fromUtf8("edit_mesh_crd"))
        self.gridLayout_4.addWidget(self.edit_mesh_crd, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.select_mesh_mtr = QtGui.QComboBox(self.groupBox_5)
        self.select_mesh_mtr.setObjectName(_fromUtf8("select_mesh_mtr"))
        self.gridLayout_6.addWidget(self.select_mesh_mtr, 0, 0, 1, 1)
        self.button_mesh_import_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_import_mtr.setMinimumSize(QtCore.QSize(100, 23))
        self.button_mesh_import_mtr.setMaximumSize(QtCore.QSize(100, 23))
        self.button_mesh_import_mtr.setObjectName(_fromUtf8("button_mesh_import_mtr"))
        self.gridLayout_6.addWidget(self.button_mesh_import_mtr, 1, 0, 1, 1)
        self.button_mesh_remove_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_remove_mtr.setMinimumSize(QtCore.QSize(90, 23))
        self.button_mesh_remove_mtr.setMaximumSize(QtCore.QSize(90, 23))
        self.button_mesh_remove_mtr.setObjectName(_fromUtf8("button_mesh_remove_mtr"))
        self.gridLayout_6.addWidget(self.button_mesh_remove_mtr, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_3.setMinimumSize(QtCore.QSize(222, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mesh_element_id_edit = QtGui.QLineEdit(self.groupBox_3)
        self.mesh_element_id_edit.setMaximumSize(QtCore.QSize(50, 30))
        self.mesh_element_id_edit.setObjectName(_fromUtf8("mesh_element_id_edit"))
        self.horizontalLayout_3.addWidget(self.mesh_element_id_edit)
        self.button_mesh_imp_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_imp_elmid.setObjectName(_fromUtf8("button_mesh_imp_elmid"))
        self.horizontalLayout_3.addWidget(self.button_mesh_imp_elmid)
        self.button_mesh_rem_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_rem_elmid.setObjectName(_fromUtf8("button_mesh_rem_elmid"))
        self.horizontalLayout_3.addWidget(self.button_mesh_rem_elmid)
        self.gridLayout_3.addWidget(self.groupBox_3, 9, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mesh_element_explorer = QtGui.QPlainTextEdit(self.groupBox_6)
        self.mesh_element_explorer.setObjectName(_fromUtf8("mesh_element_explorer"))
        self.gridLayout_7.addWidget(self.mesh_element_explorer, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 10, 0, 1, 2)
        self.horizontalLayout.addWidget(self.mesh_control)
        self.groupBox_2 = QtGui.QGroupBox(MeshSettings)
        self.groupBox_2.setMinimumSize(QtCore.QSize(328, 543))
        self.groupBox_2.setMaximumSize(QtCore.QSize(2000, 3000))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mesh_list = QtGui.QListWidget(self.groupBox_2)
        self.mesh_list.setObjectName(_fromUtf8("mesh_list"))
        self.verticalLayout_4.addWidget(self.mesh_list)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(MeshSettings)
        QtCore.QMetaObject.connectSlotsByName(MeshSettings)

    def retranslateUi(self, MeshSettings):
        MeshSettings.setWindowTitle(_translate("MeshSettings", "Form", None))
        self.mesh_control.setTitle(_translate("MeshSettings", "Import elements", None))
        self.button_mesh_import_all.setText(_translate("MeshSettings", "Import All", None))
        self.button_mesh_remove_all.setText(_translate("MeshSettings", "Remove All", None))
        self.groupBox_4.setTitle(_translate("MeshSettings", "Element Position", None))
        self.groupBox.setTitle(_translate("MeshSettings", "Axis", None))
        self.mesh_radio_x.setText(_translate("MeshSettings", "X", None))
        self.mesh_radio_y.setText(_translate("MeshSettings", "Y", None))
        self.mesh_radio_z.setText(_translate("MeshSettings", "Z", None))
        self.label_11.setText(_translate("MeshSettings", "Axis coordinate", None))
        self.button_mesh_rem_over.setText(_translate("MeshSettings", "Remove Over", None))
        self.button_mesh_imp_bellow.setText(_translate("MeshSettings", "Import Bellow", None))
        self.button_mesh_rem_bellow.setText(_translate("MeshSettings", "Remove Bellow", None))
        self.button_mesh_imp_through.setText(_translate("MeshSettings", "Import Through", None))
        self.button_mesh_rem_through.setText(_translate("MeshSettings", "Remove Through", None))
        self.button_mesh_imp_over.setToolTip(_translate("MeshSettings", "Import all elements with altitude over set height", None))
        self.button_mesh_imp_over.setText(_translate("MeshSettings", "Import Over ", None))
        self.groupBox_5.setTitle(_translate("MeshSettings", "Element Material", None))
        self.button_mesh_import_mtr.setText(_translate("MeshSettings", "Import MTR", None))
        self.button_mesh_remove_mtr.setText(_translate("MeshSettings", "Remove MTR", None))
        self.groupBox_3.setTitle(_translate("MeshSettings", "Element ID", None))
        self.button_mesh_imp_elmid.setText(_translate("MeshSettings", "Import", None))
        self.button_mesh_rem_elmid.setText(_translate("MeshSettings", "Remove", None))
        self.groupBox_6.setTitle(_translate("MeshSettings", "Element explorer", None))
        self.groupBox_2.setTitle(_translate("MeshSettings", "0 elemets in the list", None))

