# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meshsettings.ui'
#
# Created: Tue Dec 04 17:27:04 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MeshSettings(object):
    def setupUi(self, MeshSettings):
        MeshSettings.setObjectName("MeshSettings")
        MeshSettings.resize(666, 639)
        self.horizontalLayout = QtGui.QHBoxLayout(MeshSettings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mesh_control = QtGui.QGroupBox(MeshSettings)
        self.mesh_control.setMinimumSize(QtCore.QSize(250, 527))
        self.mesh_control.setMaximumSize(QtCore.QSize(250, 16777215))
        self.mesh_control.setObjectName("mesh_control")
        self.gridLayout_3 = QtGui.QGridLayout(self.mesh_control)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_mesh_import_all = QtGui.QPushButton(self.mesh_control)
        self.button_mesh_import_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_import_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_import_all.setObjectName("button_mesh_import_all")
        self.gridLayout_3.addWidget(self.button_mesh_import_all, 0, 0, 1, 1)
        self.button_mesh_remove_all = QtGui.QPushButton(self.mesh_control)
        self.button_mesh_remove_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_remove_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_remove_all.setObjectName("button_mesh_remove_all")
        self.gridLayout_3.addWidget(self.button_mesh_remove_all, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 11, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mesh_radio_x = QtGui.QRadioButton(self.groupBox)
        self.mesh_radio_x.setMaximumSize(QtCore.QSize(76, 16777215))
        self.mesh_radio_x.setObjectName("mesh_radio_x")
        self.horizontalLayout_4.addWidget(self.mesh_radio_x)
        self.mesh_radio_y = QtGui.QRadioButton(self.groupBox)
        self.mesh_radio_y.setObjectName("mesh_radio_y")
        self.horizontalLayout_4.addWidget(self.mesh_radio_y)
        self.mesh_radio_z = QtGui.QRadioButton(self.groupBox)
        self.mesh_radio_z.setObjectName("mesh_radio_z")
        self.horizontalLayout_4.addWidget(self.mesh_radio_z)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 1, 1, 1)
        self.button_mesh_rem_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_over.setObjectName("button_mesh_rem_over")
        self.gridLayout_4.addWidget(self.button_mesh_rem_over, 2, 1, 1, 1)
        self.button_mesh_imp_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_bellow.setObjectName("button_mesh_imp_bellow")
        self.gridLayout_4.addWidget(self.button_mesh_imp_bellow, 3, 0, 1, 1)
        self.button_mesh_rem_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_bellow.setObjectName("button_mesh_rem_bellow")
        self.gridLayout_4.addWidget(self.button_mesh_rem_bellow, 3, 1, 1, 1)
        self.button_mesh_imp_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_through.setObjectName("button_mesh_imp_through")
        self.gridLayout_4.addWidget(self.button_mesh_imp_through, 4, 0, 1, 1)
        self.button_mesh_rem_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_through.setObjectName("button_mesh_rem_through")
        self.gridLayout_4.addWidget(self.button_mesh_rem_through, 4, 1, 1, 1)
        self.button_mesh_imp_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_over.setMinimumSize(QtCore.QSize(102, 0))
        self.button_mesh_imp_over.setObjectName("button_mesh_imp_over")
        self.gridLayout_4.addWidget(self.button_mesh_imp_over, 2, 0, 1, 1)
        self.edit_mesh_axis_coord = QtGui.QLineEdit(self.groupBox_4)
        self.edit_mesh_axis_coord.setObjectName("edit_mesh_axis_coord")
        self.gridLayout_4.addWidget(self.edit_mesh_axis_coord, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.select_mesh_mtr = QtGui.QComboBox(self.groupBox_5)
        self.select_mesh_mtr.setObjectName("select_mesh_mtr")
        self.gridLayout_6.addWidget(self.select_mesh_mtr, 0, 0, 1, 1)
        self.button_mesh_import_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_import_mtr.setMinimumSize(QtCore.QSize(100, 23))
        self.button_mesh_import_mtr.setMaximumSize(QtCore.QSize(100, 23))
        self.button_mesh_import_mtr.setObjectName("button_mesh_import_mtr")
        self.gridLayout_6.addWidget(self.button_mesh_import_mtr, 1, 0, 1, 1)
        self.button_mesh_remove_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_remove_mtr.setMinimumSize(QtCore.QSize(90, 23))
        self.button_mesh_remove_mtr.setMaximumSize(QtCore.QSize(90, 23))
        self.button_mesh_remove_mtr.setObjectName("button_mesh_remove_mtr")
        self.gridLayout_6.addWidget(self.button_mesh_remove_mtr, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_3.setMinimumSize(QtCore.QSize(222, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mesh_element_id_edit = QtGui.QLineEdit(self.groupBox_3)
        self.mesh_element_id_edit.setMaximumSize(QtCore.QSize(50, 30))
        self.mesh_element_id_edit.setObjectName("mesh_element_id_edit")
        self.horizontalLayout_3.addWidget(self.mesh_element_id_edit)
        self.button_mesh_imp_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_imp_elmid.setObjectName("button_mesh_imp_elmid")
        self.horizontalLayout_3.addWidget(self.button_mesh_imp_elmid)
        self.button_mesh_rem_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_rem_elmid.setObjectName("button_mesh_rem_elmid")
        self.horizontalLayout_3.addWidget(self.button_mesh_rem_elmid)
        self.gridLayout_3.addWidget(self.groupBox_3, 9, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.mesh_element_explorer = QtGui.QPlainTextEdit(self.groupBox_6)
        self.mesh_element_explorer.setObjectName("mesh_element_explorer")
        self.gridLayout_7.addWidget(self.mesh_element_explorer, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 10, 0, 1, 2)
        self.horizontalLayout.addWidget(self.mesh_control)
        self.groupBox_2 = QtGui.QGroupBox(MeshSettings)
        self.groupBox_2.setMinimumSize(QtCore.QSize(328, 543))
        self.groupBox_2.setMaximumSize(QtCore.QSize(2000, 3000))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mesh_list = QtGui.QListWidget(self.groupBox_2)
        self.mesh_list.setObjectName("mesh_list")
        self.verticalLayout_4.addWidget(self.mesh_list)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(MeshSettings)
        QtCore.QMetaObject.connectSlotsByName(MeshSettings)

    def retranslateUi(self, MeshSettings):
        MeshSettings.setWindowTitle(QtGui.QApplication.translate("MeshSettings", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_control.setTitle(QtGui.QApplication.translate("MeshSettings", "Import elements", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_import_all.setText(QtGui.QApplication.translate("MeshSettings", "Import All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_remove_all.setText(QtGui.QApplication.translate("MeshSettings", "Remove All", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MeshSettings", "Element Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MeshSettings", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_radio_x.setText(QtGui.QApplication.translate("MeshSettings", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_radio_y.setText(QtGui.QApplication.translate("MeshSettings", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_radio_z.setText(QtGui.QApplication.translate("MeshSettings", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MeshSettings", "Axis coordinate", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_over.setText(QtGui.QApplication.translate("MeshSettings", "Remove Over", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_bellow.setText(QtGui.QApplication.translate("MeshSettings", "Import Bellow", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_bellow.setText(QtGui.QApplication.translate("MeshSettings", "Remove Bellow", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_through.setText(QtGui.QApplication.translate("MeshSettings", "Import through", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_through.setText(QtGui.QApplication.translate("MeshSettings", "Remove Through", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_over.setToolTip(QtGui.QApplication.translate("MeshSettings", "Import all elements with altitude over set height", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_over.setText(QtGui.QApplication.translate("MeshSettings", "Import Over ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MeshSettings", "Element Material", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_import_mtr.setText(QtGui.QApplication.translate("MeshSettings", "Import MTR", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_remove_mtr.setText(QtGui.QApplication.translate("MeshSettings", "Remove MTR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MeshSettings", "Element ID", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_elmid.setText(QtGui.QApplication.translate("MeshSettings", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_elmid.setText(QtGui.QApplication.translate("MeshSettings", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MeshSettings", "Element explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MeshSettings", "0 elemets in the list", None, QtGui.QApplication.UnicodeUTF8))

