# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensitivity.ui'
#
# Created: Tue Dec 04 17:50:55 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Sensitivity(object):
    def setupUi(self, Sensitivity):
        Sensitivity.setObjectName("Sensitivity")
        Sensitivity.resize(590, 606)
        self.horizontalLayout = QtGui.QHBoxLayout(Sensitivity)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_sens_1 = QtGui.QGroupBox(Sensitivity)
        self.groupBox_sens_1.setObjectName("groupBox_sens_1")
        self.formLayout = QtGui.QFormLayout(self.groupBox_sens_1)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_sens_mult_1 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_1.setObjectName("label_sens_mult_1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_sens_mult_1)
        self.edit_sens_mult_1 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_1.setObjectName("edit_sens_mult_1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_1)
        self.label_sens_mult_2 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_2.setObjectName("label_sens_mult_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_sens_mult_2)
        self.edit_sens_mult_2 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_2.setObjectName("edit_sens_mult_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_2)
        self.label_sens_mult_3 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_3.setObjectName("label_sens_mult_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_sens_mult_3)
        self.edit_sens_mult_3 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_3.setObjectName("edit_sens_mult_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_3)
        self.label_sens_mult_4 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_4.setObjectName("label_sens_mult_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_sens_mult_4)
        self.edit_sens_mult_4 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_4.setObjectName("edit_sens_mult_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_4)
        self.label_sens_mult_5 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_5.setObjectName("label_sens_mult_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_sens_mult_5)
        self.edit_sens_mult_5 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_5.setObjectName("edit_sens_mult_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_5)
        self.label_sens_mult_6 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_6.setObjectName("label_sens_mult_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_sens_mult_6)
        self.edit_sens_mult_6 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_6.setObjectName("edit_sens_mult_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_6)
        self.label_sens_mult_7 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_7.setObjectName("label_sens_mult_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_sens_mult_7)
        self.edit_sens_mult_7 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_7.setObjectName("edit_sens_mult_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_7)
        self.label_sens_mult_8 = QtGui.QLabel(self.groupBox_sens_1)
        self.label_sens_mult_8.setObjectName("label_sens_mult_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_sens_mult_8)
        self.edit_sens_mult_8 = QtGui.QLineEdit(self.groupBox_sens_1)
        self.edit_sens_mult_8.setObjectName("edit_sens_mult_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.edit_sens_mult_8)
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_sens_1)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edit_sens_output_dir = QtGui.QLineEdit(self.groupBox_13)
        self.edit_sens_output_dir.setObjectName("edit_sens_output_dir")
        self.horizontalLayout_8.addWidget(self.edit_sens_output_dir)
        self.tool_sens_output_dir = QtGui.QToolButton(self.groupBox_13)
        self.tool_sens_output_dir.setObjectName("tool_sens_output_dir")
        self.horizontalLayout_8.addWidget(self.tool_sens_output_dir)
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.groupBox_13)
        self.groupBox_sens_3 = QtGui.QGroupBox(self.groupBox_sens_1)
        self.groupBox_sens_3.setTitle("")
        self.groupBox_sens_3.setObjectName("groupBox_sens_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_sens_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_sens_start = QtGui.QPushButton(self.groupBox_sens_3)
        self.button_sens_start.setObjectName("button_sens_start")
        self.horizontalLayout_7.addWidget(self.button_sens_start)
        self.button_sens_save = QtGui.QPushButton(self.groupBox_sens_3)
        self.button_sens_save.setObjectName("button_sens_save")
        self.horizontalLayout_7.addWidget(self.button_sens_save)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.groupBox_sens_3)
        self.horizontalLayout.addWidget(self.groupBox_sens_1)
        self.groupBox_sens_2 = QtGui.QGroupBox(Sensitivity)
        self.groupBox_sens_2.setObjectName("groupBox_sens_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_sens_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.list_sens_mtr = QtGui.QListWidget(self.groupBox_sens_2)
        self.list_sens_mtr.setObjectName("list_sens_mtr")
        self.verticalLayout_6.addWidget(self.list_sens_mtr)
        self.horizontalLayout.addWidget(self.groupBox_sens_2)

        self.retranslateUi(Sensitivity)
        QtCore.QMetaObject.connectSlotsByName(Sensitivity)

    def retranslateUi(self, Sensitivity):
        Sensitivity.setWindowTitle(QtGui.QApplication.translate("Sensitivity", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_sens_1.setTitle(QtGui.QApplication.translate("Sensitivity", "Multiplicator form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_1.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_2.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_3.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_4.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_5.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_6.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_7.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sens_mult_8.setText(QtGui.QApplication.translate("Sensitivity", "Multiplicator #8", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("Sensitivity", "Output Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_sens_output_dir.setText(QtGui.QApplication.translate("Sensitivity", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.button_sens_start.setText(QtGui.QApplication.translate("Sensitivity", "Compute", None, QtGui.QApplication.UnicodeUTF8))
        self.button_sens_save.setText(QtGui.QApplication.translate("Sensitivity", "Generate tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_sens_2.setTitle(QtGui.QApplication.translate("Sensitivity", "List of materials", None, QtGui.QApplication.UnicodeUTF8))

